import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Demo App",
  viewport: "width=device-width, initial-scale=1.0",
  description: "Generated by create next app"
};

export function DocumentHead() {
  return (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>meinUnterricht</title>
    </>
  );
}
